theme: jekyll-theme-minimal
logo: "/images/pyticchio.png"
title: Alessandro Paticchio
description: Computer Science student @Polimi, passionate about Data Science and Machine Learning. Former research fellow @Iacs, Harvard.
