theme: jekyll-theme-minimal
title: Alessandro Paticchio
avatar: "/images/pyticchio.png"
description: Computer Science student @Polimi, passionate about Data Science and Machine Learning. Former research fellow @Iacs, Harvard.
