theme: jekyll-theme-minimal
title: Hello, my name is Alessandro!
logo: "/images/pyticchio.png"
description: "Computer Science student @Polimi, passionate about Data Science and Machine Learning. Former research fellow @Iacs, Harvard.
