theme: jekyll-theme-minimal
title: Alessandro Paticchio
logo: "/images/me.png"
email: alessandropaticchio@gmail.com
description: Data Scientist @Casavo. Former research fellow at IACS @Harvard. Computer Science graduate @Polimi, passionate about Data Science and Machine Learning. <br> <a href="https://alessandropaticchio.github.io/#ciao">Intro</a> <br> <a href="https://alessandropaticchio.github.io/#-currently-working-at">Currently at...</a>  <br> <a href="https://alessandropaticchio.github.io/#exclamation-most-relevant-personal-projects">Personal projects</a><br> <a href="https://alessandropaticchio.github.io/#snake-skills">Skills</a> <br> <a href="https://alessandropaticchio.github.io/#newspaper-main-blogposts-i-published">Blogposts</a  
plugins:
  - jemoji
