theme: jekyll-theme-minimal
title: Alessandro Paticchio
logo: "/images/me.png"
email: alessandropaticchio@gmail.com
description: Data Scientist @Moviri. Former research fellow at IACS @Harvard. Computer Science graduate @Polimi, passionate about Data Science and Machine Learning. 
plugins:
  - jemoji
